#!/bin/bash

INFILE="$HOME/git/rust-lang/mdBook/src/theme/index.hbs"

########################################
# Make sure the files we need, exist

FAIL=false
for f in "$INFILE" ./mdbook-index-template
do
    if ! [[ -f "$f" ]]
    then
        echo "ERROR: '$f' does not exist, cannot continue"
        FAIL=true
    fi
done

if $FAIL
then
    exit 1
fi

########################################
# Do the deed
# -t: add commit info below table of contents
# -p: add commit info below main page contents

./mdbook-index-template -tp "$INFILE" > index-template.hbs
